@extends('front_end.layout.app',['title_data'=>$title_data, 'footer_left'=>$footer_left, 'footer_right'=>$footer_right])
@section('content')
<!--banner-sec-->
@include('front_end.HomePage.Banner')
<!--banner-sec-->
<!--about-sec-->
@include('front_end.HomePage.aboutUs')
<!--about-sec-->
<!--service-sec-->
@include('front_end.HomePage.service')
<!--service-sec-->
<!--business-sec-->
@include('front_end.HomePage.business')
<!--business-sec-->
<!--static-sec-->
@include('front_end.HomePage.static')
<!--static-sec-->
<!--case-sec-->
@include('front_end.HomePage.case_studies')
<!--case-sec-->
<!--testimonials-sec-->
@include('front_end.HomePage.review')
<!--testimonials-sec-->
<!--blog-sec-->
@include('front_end.HomePage.news')
<!--form-sec-->
@include('front_end.contact.contact')
@endsection